name: API-тесты Newman CLI
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Проверка репозитория
      - uses: actions/checkout@v3
      - name: Создать каталог
        run: |
          mkdir TestArtifact
      # Установка Node
      - name: install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      # Установка Newman, репортер для Slack и HTML-репортер
      - name: install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra
      # Запуск коллекции
      - name: Запустить тесты
        run: newman run ".github/workflows/ request.json" -e ".github/workflows/environment.json" -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html
      # Загрузить отчеты в каталог TestArtifacts
      - name: Вывести результаты
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: testArtifacts
